### ISSUE TITLE
Add Language bar under the buttons of the files: index.html & GoogleImageSearch.html

### ISSUE THREAD

**Issue by sunami09** [Multiprocessing-Muggles/Google-Clone#5]
<b>Styling Should be Identical to the Google Home page. Use HTML and CSS only. Don't change any class names or id names of existing tags.</b>
![image](https://user-images.githubusercontent.com/66564001/173391335-d7d58a87-244a-49f6-89cb-19123122a0be.png)

**Comment by sukalyanbisui** [comment]
assign me to this issue

**Comment by sunami09** [comment]
Solved by @sukalyanbisui .
