### ISSUE TITLE
Replace the simple looking hyperlink references with icons suitable to their names.

### ISSUE THREAD

**Issue by sunami09** [Multiprocessing-Muggles/Google-Clone#6]
### Change this with some beautiful icons, maybe add hover effect on it:
![image](https://user-images.githubusercontent.com/66564001/173392726-a24046fe-168d-4df0-b9b8-f1b96f649321.png)

**Comment by dikshita-mehta** [comment]
I would like to work on this issue

**Comment by sunami09** [comment]
@dikshita-mehta I have assigned you to this issue. Try to create a pull request by this week or this issue will be reassigned to someone else!

**Comment by sunami09** [comment]
@dikshita-mehta your code was Ok but you haven't uploaded images/icons in the image folder. That's why it is not accessible.

**Comment by sunami09** [comment]
Resolved By @dikshita-mehta.
